version: '2'

services:
  monarch:
    image: kw1073/monarch:${TAG_VERSION}
    ports:
      - "5000:5000"
    environment:
      C_FORCE_ROOT: "true"
      LANG: C.UTF-8
    volumes:
      -  /etc/localtime:/etc/localtime
      - ./local_settings.py:/app/local_settings.py
    restart: always
    command: /usr/local/bin/gunicorn -c gunicorn_config.py monarch.wsgi:application
